---
- hosts: local
  
  tasks:
    - name: Generate configuration file
      template: src=~/ANSIBLE/acc_sw_tmplt.j2
                  dest=~/ANSIBLE/CFGS/{{item.hostname}}.txt
      with_items:
        - {hostname: my-rtr1, ip_addr: 10.1.1.1, default_gateway: 10.1.1.10, secret: My!Secret*, access_vlan: 100, snmp_community: readme*gently, SNMPV3: false }
        - {hostname: my-rtr2, ip_addr: 10.1.2.1, default_gateway: 10.1.2.10, secret: My!Secret*, access_vlan: 100, snmp_community: readme*gently, SNMPV3: false }
        - {hostname: my-rtr3, ip_addr: 10.1.3.1, default_gateway: 10.1.3.10, secret: My!Secret*, access_vlan: 100, snmp_community: readme*gently, SNMPV3: false }
        - {hostname: my-rtr4, ip_addr: 10.1.4.1, default_gateway: 10.1.4.10, secret: My!Secret*, access_vlan: 100, snmp_community: readme*gently, SNMPV3: false }
        - {hostname: my-rtr5, ip_addr: 10.1.5.1, default_gateway: 10.1.5.10, secret: My!Secret*, access_vlan: 100, snmp_community: readme*gently, SNMPV3: true }

